### ISSUE TITLE
Default h2 config does not run

### ISSUE THREAD

**Issue by harry1453** [burst-apps-team/burstcoin#13]
```
org.h2.jdbc.JdbcSQLException: A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:file:/db/burst;DB_CLOSE_ON_EXIT=FALSE". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:400)
	at org.h2.engine.Engine.openSession(Engine.java:49)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:365)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:194)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:460)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:534)
	... 6 more
```

Fix: Change database URL from `jdbc:h2:file:/db/burst;DB_CLOSE_ON_EXIT=FALSE` to `jdbc:h2:file:./db/burst;DB_CLOSE_ON_EXIT=FALSE`

**Comment by llybin** [comment]
Looks like mistake in README:

`docker run -p 8123:8123 -p 8125:8125 -v "$(pwd)"/burst_db:/db -d burstappsteam/burstcoin:2-h2`

https://github.com/burst-apps-team/burstcoin/blob/develop/Dockerfile.h2

Volumes already defined: 
`VOLUME ["/conf", "/db"]`

https://github.com/burst-apps-team/burstcoin/blob/develop/conf/brs.properties.h2

BD configured in config right, on volume /db
`DB.Url=jdbc:h2:file:/db/burst;DB_CLOSE_ON_EXIT=FALSE`

Needed run usin this command:
`docker run -p 8123:8123 -p 8125:8125 -d burstappsteam/burstcoin:2-h2`

I've checked:
``` 
docker exec -ti <> mount | grep db
/dev/sda2 on /db type ext4 (rw,lazytime,relatime,discard)
```

```
docker exec -ti <> ls /db
burst.mv.db
```

```
docker volume ls
docker volume inspect
ls <Mountpoint>
burst.mv.db
```

Everything looks right, now. DB in Volume.

**Comment by harry1453** [comment]
Thanks! Could you create a PR for this?

**Comment by felixbrucker** [comment]
This seems like a different issue. The error noted in this issue is 
```
A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:file:/db/burst;DB_CLOSE_ON_EXIT=FALSE".
```
`/db/burst_db` is clearly not a relative path but an absolute one.

That being said with the command in the README i could start a h2 container without any issues:
```
docker run --rm -p 8123:8123 -p 8125:8125 -v "$(pwd)"/burst_db:/db burstappsteam/burstcoin:2-h2
Mar 11, 2019 10:21:37 AM brs.Burst loadProperties
INFO: Initializing Burst Reference Software (BRS) version v2.3.0
Mar 11, 2019 10:21:37 AM org.ehcache.core.EhcacheManager createCache
INFO: Cache 'account' created in EhcacheManager.
[INFO] 2019-03-11 10:21:38 brs.Burst - DB.Username undefined. Default: ><
[INFO] 2019-03-11 10:21:38 brs.Burst - DB.Password undefined. Default: ><
[INFO] 2019-03-11 10:21:38 brs.db.sql.Db - Running flyway migration
[INFO] 2019-03-11 10:21:38 brs.db.sql.Db - Using SQL Backend with Dialect H2
...
[INFO] 2019-03-11 10:21:45 brs.Burst - Initialization took 7977 ms
[INFO] 2019-03-11 10:21:45 brs.Burst - BRS v2.3.0 started successfully.
```

The volume override in the cli command was/is there so that beginners can easily see their files and stuff, it can of course be omitted, then the volume is used.

The only time i had issues with this was when running docker on windows where `$(pwd)` doesn't work.

Can you confirm this also happened for you on linux, or was it a windows docker environment?
^ @harry1453 @llybin

**Comment by llybin** [comment]
pwd is unix command which return current directory.

https://stackoverflow.com/questions/921741/windows-equivalent-to-unix-pwd

Yes, command `docker run -p 8123:8123 -p 8125:8125 -v "$(pwd)"/burst_db:/db -d burstappsteam/burstcoin:2-h2` overrides Volume /db (defined in Dockerfile) on local folder burst_db.

It's necessary write two manual, or hope that the user knows what is it Volume and where located his files. From my experience, maintaining similar compatibility is a pain. Specific user let modifies. He can run this command every time from new current directory and will get many copies DB.

**Comment by felixbrucker** [comment]
That may be a valid point, but not related to the issue described here. The issue hat hand is that brs thinks the absolute path `/db/burst_db` is relative and changing the volume override is not the correct fix for that, its just side effect from how volumes and bind mounts work on windows.

I agree we could remove the volume override in the readme, but we should also verify why this error happens and how to properly fix it (albeit i still think its due to the pwd not working (correctly) on windows). That being said i personally think we should remove h2 completely and only support mariadb/mysql, at least for docker.
