### ISSUE TITLE
GUI Display issues

### ISSUE THREAD

**Issue by holycow131415** [burst-apps-team/burstcoin#22]
- [x]  The change view from 24 hour option doesnt toggle the view under firefox, chrome, etc, nor under qbundle. It also has a graphical black glitch in the drop down. https://github.com/PoC-Consortium/Qbundle/issues/67

- [x] Assets never load under Qbundle. It appears to be the wallet doesnt like the chromium pocket browser. https://github.com/PoC-Consortium/Qbundle/issues/66

**Comment by harry1453** [comment]
Thanks for opening this issue. I have managed to fix the bug where the 24h view toggle did not function, however I have not been able to reproduce the black box behaviour. Regarding your second point, as we are no longer supporting QBundle in favor of our upcoming multi-platform loosely-coupled frontend Phoenix, we will not investigate this issue unless it can be reproduced outside of QBundle (sorry 😞 ). The fix for the 24h bug should be available in the next version.

**Comment by holycow131415** [comment]
Nice thanks. Sounds good. Now i just run qbundle in the background and access the wallet in the browser now anyway.
