### ISSUE TITLE
Why are two signatures "blockSignature" and "generationSignature" included in the block

### ISSUE THREAD

**Issue by saizhenzhu** [burst-apps-team/burstcoin#384]
Why are two signatures "blockSignature" and "generationSignature" included in the block, I don't understand why it is needed? Can you help explain?

**Comment by saizhenzhu** [comment]
please...

**Comment by harry1453** [comment]
Generation signature is that hash of the last block's generation signature and generator ID - it is part of the data that in mining. "signature" is not the right word here because it isn't a signature at all. But it is still called that for backwards compatibility.

Block signature is the cryptographic signature of the serialized contents of the block by the signer (either the generator or their pool)

**Comment by saizhenzhu** [comment]
I seem to understand a bit, maybe I don't understand the POC mining process. thank you very much.

This is what I translated with Google.^_^

**Comment by harry1453** [comment]
Ah okay, you're welcome! The misleading thing here is that generationSignature is not actually a signature. BlockSignature is the real signature. That might translate a bit better.

**Comment by harry1453** [comment]
I'll close for now as you seem happy that the question has been answered.
