### ISSUE TITLE
BRS 2.5.1 sorts 12am transactions out of order

### ISSUE THREAD

**Issue by paulpoco** [burst-apps-team/burstcoin#439]
0 is listed after 3am when it should be before.
![image](https://user-images.githubusercontent.com/801414/85210330-d2b38980-b2f3-11ea-8195-8a14e68c79c8.png)
![image](https://user-images.githubusercontent.com/801414/84725840-67a73300-af40-11ea-8dfe-4b59afef79de.png)

**Comment by jjos2372** [comment]
Please give more information on what is this, transactions, blocks, ...?

**Comment by paulpoco** [comment]
> Please give more information on what is this, transactions, blocks, ...?

It is right in the screengrab above.  It is list oldest on bottom and newest on top.

It lists 3am then 0am then 7pm.  It should be 0am then 3am then 7pm.

Has nothing to do with any transactions or blocks.

**Comment by jjos2372** [comment]
Sorry, but is this the dashboard, the transactions panel on BRS wallet or what? You sent just a small screen portion and I cannot find it.

Recalling that nothing related with transactions has been changed in a while, so not a 2.5.X specific issue.

**Comment by jjos2372** [comment]
If this is indeed the transactions panel, where you should see something like this:
![image](https://user-images.githubusercontent.com/31958515/85210882-220cb080-b31a-11ea-8857-29279397d756.png)

Transactions are sorted primarily per block (right most column, so that more recently confirmed transactions come first) and then inside the block. Not by the timestamp of transaction generation.

Please confirm if this is the case and close the issue if appropriate.

**Comment by paulpoco** [comment]
It just looks funny when sorted by block when the block isn't listed.

**Comment by jjos2372** [comment]
I mean they are sorted by the number of confirmations, latest column (the more confirmations the older is the block).
