### ISSUE TITLE
CIP 27 & CIP 29 --> Kill this coin now please

### ISSUE THREAD

**Issue by xerxes1986** [burst-apps-team/burstcoin#488]
Y'all be implementing FOUNDATIONAL SHIFTING ideas without any sort of democratic consensus.

Just because you control the github, doesn't mean you control the coin.

Where was the informed consensus for these big changes?

CIP 29 changes this currency into a INFLATIONARY one rather than DEFLATIONARY....removing fundamental value for many crypto investors.

CIP 27 then takes these new INFLATIONARY coins to those who already have a lot of coins (rich getting richer). As a prime counterexample to how this impacts a 'normal Burst supporter/miner'...I have been mining for the better part of 3.5 years, and I have only earned about 30,000 Burst using my 50TB of disks! A very crappy return on investment...and if I were to 'commit' my whole stack I would still get the same penalty as if I didn't stake at all. I might as well replot them for CHIA now!

I fail to see how these changes will bring new miners/investors/users to the coin. Instead of focusing time/energy on actual value-adding features the community has been asking for for years...we get this hot garbage. 0/10

**Comment by jjos2372** [comment]
Thanks for reaching out. Apparently it is your first issue/comment here. Exactly as you mentioned, past situation make almost impossible to mine the coin or have any profit. On top of that, a single pool had more than 60% of capacity. So this has being discussed for one year since past upgrade.

Both these issues are now solved with the latest upgrade. Feel free to suggest other improvements, help on critical issues or any other activities. FYI we are having many more new people interested in the recent weeks than in the entire past year. You can also probably check the market YTD, which was 2 sats not long ago.
